// Reads client/src/assets/logo.png and writes client/src/lib/brand-logo.ts
// containing the base64 data URL. Run once whenever the logo changes:
//   node scripts/encode-logo.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(__dirname, "..");
const logoPath = resolve(projectRoot, "client/src/assets/logo.png");
const outPath = resolve(projectRoot, "client/src/lib/brand-logo.ts");

const bytes = readFileSync(logoPath);
const b64 = bytes.toString("base64");
const dataUrl = `data:image/png;base64,${b64}`;

const fileBody = `// AUTO-GENERATED by scripts/encode-logo.mjs — do not edit by hand.
// Source: client/src/assets/logo.png
export const SEVEN_RFP_LOGO_DATA_URL = "${dataUrl}";
`;

writeFileSync(outPath, fileBody);
console.log(
  `Wrote ${outPath} (${(bytes.length / 1024).toFixed(1)} KB raw → ${(b64.length / 1024).toFixed(1)} KB base64).`
);
